<?php
/**
 * OryZenX Domain Marketplace - Installation Script
 * Auto Database Setup & Configuration
 */

// Disable error display during installation
ini_set('display_errors', 0);
error_reporting(E_ALL);

// Default database configuration
$db_host = 'localhost';
$db_user = 'root';
$db_pass = '';
$db_name = 'oryzenx_marketplace';

// Check if already installed
if (file_exists(__DIR__ . '/installed.lock')) {
    die('Installation already completed. Delete installed.lock to reinstall.');
}

// Check for POST request
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_host = sanitizeInput($_POST['db_host'] ?? 'localhost');
    $db_user = sanitizeInput($_POST['db_user'] ?? 'root');
    $db_pass = $_POST['db_pass'] ?? '';
    $db_name = sanitizeInput($_POST['db_name'] ?? 'oryzenx_marketplace');
    $admin_email = sanitizeInput($_POST['admin_email'] ?? '');
    $admin_password = $_POST['admin_password'] ?? '';

    if (!$admin_email || !$admin_password) {
        $error = 'Admin email and password are required';
    } else {
        // Try to connect and install
        $result = installDatabase($db_host, $db_user, $db_pass, $db_name, $admin_email, $admin_password);
        if ($result['success']) {
            // Create config file\n            createConfigFile($db_host, $db_user, $db_pass, $db_name);
            // Create installed lock
            file_put_contents(__DIR__ . '/installed.lock', date('Y-m-d H:i:s'));
            $success = $result['message'];\n        } else {
            $error = $result['message'];
        }
    }
}

function sanitizeInput($input) {
    return htmlspecialchars(trim($input), ENT_QUOTES, 'UTF-8');
}

function installDatabase($host, $user, $pass, $db_name, $admin_email, $admin_password) {
    try {
        // Connect to MySQL server
        $conn = new PDO("mysql:host=$host", $user, $pass, array(
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ));

        // Create database
        $conn->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $conn->exec("USE `$db_name`");

        // Read schema file
        $schema = file_get_contents(__DIR__ . '/database/schema.sql');
        
        // Execute schema
        $statements = explode(';', $schema);
        foreach ($statements as $statement) {
            $statement = trim($statement);
            if (!empty($statement)) {
                $conn->exec($statement);
            }
        }

        // Hash admin password
        $hashed_password = password_hash($admin_password, PASSWORD_BCRYPT, array('cost' => 12));

        // Create admin user
        $stmt = $conn->prepare("INSERT INTO users (full_name, email, password, is_admin, status) VALUES (?, ?, ?, 1, 'active')");
        $stmt->execute(array('Administrator', $admin_email, $hashed_password));

        return array('success' => true, 'message' => 'Installation completed successfully!');
    } catch (PDOException $e) {
        return array('success' => false, 'message' => 'Database Error: ' . $e->getMessage());
    }
}

function createConfigFile($host, $user, $pass, $db_name) {
    $config = "<?php\n";
    $config .= "// Database Configuration - Generated by installer\n";
    $config .= "define('DB_HOST', '$host');\n";
    $config .= "define('DB_USER', '$user');\n";
    $config .= "define('DB_PASS', '$pass');\n";
    $config .= "define('DB_NAME', '$db_name');\n";
    $config .= "?>\n";
    
    file_put_contents(__DIR__ . '/config.php', $config);
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OryZenX - Installation Wizard</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }
        .container {
            background: #0f3460;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 10px 40px rgba(0, 0, 0, 0.3);
            max-width: 500px;
            width: 100%;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #00d4ff;
            font-size: 28px;
            margin-bottom: 5px;
        }
        .header p {
            color: #999;
            font-size: 14px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            color: #ccc;
            margin-bottom: 8px;
            font-weight: 500;
            font-size: 14px;
        }
        input, select {
            width: 100%;
            padding: 12px;
            border: 1px solid #444;
            border-radius: 5px;
            background: #1a1a2e;
            color: #fff;
            font-size: 14px;
            transition: border-color 0.3s;
        }
        input:focus, select:focus {
            outline: none;
            border-color: #00d4ff;
            box-shadow: 0 0 5px rgba(0, 212, 255, 0.3);
        }
        .btn {
            width: 100%;
            padding: 12px;
            background: linear-gradient(135deg, #00d4ff 0%, #0099cc 100%);
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: transform 0.2s, box-shadow 0.2s;
            margin-top: 20px;
        }
        .btn:hover {
            transform: translateY(-2px);\n            box-shadow: 0 5px 20px rgba(0, 212, 255, 0.4);
        }
        .alert {
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            font-size: 14px;
        }
        .alert-success {
            background: #28a745;
            color: #fff;
            border: 1px solid #20c997;
        }
        .alert-danger {
            background: #dc3545;
            color: #fff;
            border: 1px solid #e74c3c;
        }
        .info {
            background: #1a1a2e;
            border: 1px solid #00d4ff;
            color: #00d4ff;
            padding: 15px;
            border-radius: 5px;
            font-size: 13px;
            margin-bottom: 20px;
            line-height: 1.6;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>⚡ OryZenX</h1>
            <p>Domain Marketplace Installation</p>
        </div>

        <?php if (isset($success)): ?>
            <div class="alert alert-success">
                <strong>✓ Success!</strong><br>
                <?php echo $success; ?><br><br>
                <a href="public/index.php" style="color: #fff; text-decoration: underline;">Go to Dashboard</a>
            </div>
        <?php elseif (isset($error)): ?>
            <div class="alert alert-danger">
                <strong>✗ Error!</strong><br>
                <?php echo $error; ?>
            </div>
        <?php endif; ?>

        <div class="info">
            💡 Configure your database connection and create an admin account below. Make sure your MySQL server is running.
        </div>

        <form method="POST">
            <div class="form-group">
                <label for="db_host">Database Host</label>
                <input type="text" id="db_host" name="db_host" value="<?php echo $db_host; ?>" required>
            </div>

            <div class="form-group">
                <label for="db_user">Database Username</label>
                <input type="text" id="db_user" name="db_user" value="<?php echo $db_user; ?>" required>
            </div>

            <div class="form-group">
                <label for="db_pass">Database Password</label>
                <input type="password" id="db_pass" name="db_pass" value="<?php echo $db_pass; ?>">
            </div>

            <div class="form-group">
                <label for="db_name">Database Name</label>
                <input type="text" id="db_name" name="db_name" value="<?php echo $db_name; ?>" required>
            </div>

            <hr style="border: 1px solid #444; margin: 30px 0;">

            <div class="form-group">
                <label for="admin_email">Admin Email</label>
                <input type="email" id="admin_email" name="admin_email" placeholder="admin@example.com" required>
            </div>

            <div class="form-group">
                <label for="admin_password">Admin Password</label>
                <input type="password" id="admin_password" name="admin_password" placeholder="At least 8 characters" required>
            </div>

            <button type="submit" class="btn">Start Installation</button>
        </form>
    </div>
</body>
</html>